# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582add4df41f40be8a77992f9da0fb268842c0ae7a212a240afaf312afbdbe4cfb4d8e78802490b204668385e8b57f38284619cbd1253a6ff0af30f0859f406c

test:
  secret_key_base: 95d89e41aea5a40e1000af53769a63c1fa40c08a21c868541734ba48d7e5f0ac84fd472fd8d4db4dee2c9db608d12a822e6fb52ea095ba63744a221da92b62a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
